/* eslint-disable */
// Generated by `npm run generate:enums -w web`.
// Source of truth: api/src/domain/enums.js
// Do not edit manually; edit the backend enum source and regenerate.

export const PROJECT_STATUSES = [
  "planning",
  "active",
  "on_hold",
  "done",
  "archived",
] as const;

export const REQUIREMENT_STATUSES = [
  "draft",
  "reviewing",
  "approved",
  "in_dev",
  "testing",
  "accepted",
  "closed",
  "cancelled",
] as const;

export const REQUIREMENT_PRIORITIES = [
  "high",
  "medium",
  "low",
] as const;

export const TASK_STATUSES = [
  "todo",
  "in_progress",
  "blocked",
  "code_review",
  "testing",
  "acceptance",
  "done",
  "cancelled",
] as const;

export const TASK_TYPES = [
  "epic",
  "story",
  "task",
  "bug",
  "milestone",
  "work_package",
] as const;

export const SPRINT_STATUSES = [
  "planned",
  "active",
  "closed",
] as const;

export const TEST_CASE_STATUSES = [
  "draft",
  "active",
  "passed",
  "failed",
  "blocked",
] as const;

export const TEST_RUN_RESULTS = [
  "passed",
  "failed",
  "blocked",
] as const;

export const DEFECT_STATUSES = [
  "new",
  "confirmed",
  "in_fix",
  "resolved",
  "verified",
  "closed",
  "rejected",
] as const;

export const DEFECT_SEVERITIES = [
  "low",
  "medium",
  "high",
  "critical",
] as const;

export const BUILD_STATUSES = [
  "building",
  "testing",
  "released",
  "failed",
] as const;

export const RELEASE_STATUSES = [
  "draft",
  "staging",
  "released",
  "rollback",
] as const;

export const RELEASE_TYPES = [
  "official",
  "stable",
  "hotfix",
] as const;

export const RELEASE_APPROVAL_DECISIONS = [
  "approve",
  "reject",
] as const;

export const DOCUMENT_CATEGORIES = [
  "project",
  "general",
  "announcement",
] as const;

export const DOCUMENT_TYPES = [
  "requirement",
  "design",
  "test",
  "bid",
  "report",
  "other",
] as const;

export const USER_ROLES = [
  "admin",
  "pm",
  "pdm",
  "dev",
  "qa",
] as const;

export const USER_STATUSES = [
  "active",
  "disabled",
] as const;

export const WORK_ITEM_ROLES = [
  "pm",
  "pdm",
  "dev",
  "qa",
] as const;

export const AI_JOB_STATUSES = [
  "queued",
  "running",
  "awaiting_review",
  "confirmed",
  "rejected",
  "failed",
  "retried",
] as const;

export const SERVER_ENUMS = {
  projectStatuses: PROJECT_STATUSES,
  requirementStatuses: REQUIREMENT_STATUSES,
  requirementPriorities: REQUIREMENT_PRIORITIES,
  taskStatuses: TASK_STATUSES,
  taskTypes: TASK_TYPES,
  sprintStatuses: SPRINT_STATUSES,
  testCaseStatuses: TEST_CASE_STATUSES,
  testRunResults: TEST_RUN_RESULTS,
  defectStatuses: DEFECT_STATUSES,
  defectSeverities: DEFECT_SEVERITIES,
  buildStatuses: BUILD_STATUSES,
  releaseStatuses: RELEASE_STATUSES,
  releaseTypes: RELEASE_TYPES,
  releaseApprovalDecisions: RELEASE_APPROVAL_DECISIONS,
  documentCategories: DOCUMENT_CATEGORIES,
  documentTypes: DOCUMENT_TYPES,
  userRoles: USER_ROLES,
  userStatuses: USER_STATUSES,
  workItemRoles: WORK_ITEM_ROLES,
  aiJobStatuses: AI_JOB_STATUSES,
} as const;

export type ServerEnumName = keyof typeof SERVER_ENUMS;
export type ServerEnumValue<T extends ServerEnumName> = (typeof SERVER_ENUMS)[T][number];
