const fs = require("node:fs");
const path = require("node:path");
const { publicEnums } = require("../../api/src/domain/enums");

const OUTPUT_FILE = path.resolve(__dirname, "../src/constants/serverEnums.generated.ts");

const EXPORT_NAMES = {
  projectStatuses: "PROJECT_STATUSES",
  requirementStatuses: "REQUIREMENT_STATUSES",
  requirementPriorities: "REQUIREMENT_PRIORITIES",
  taskStatuses: "TASK_STATUSES",
  taskTypes: "TASK_TYPES",
  sprintStatuses: "SPRINT_STATUSES",
  testCaseStatuses: "TEST_CASE_STATUSES",
  testRunResults: "TEST_RUN_RESULTS",
  defectStatuses: "DEFECT_STATUSES",
  defectSeverities: "DEFECT_SEVERITIES",
  buildStatuses: "BUILD_STATUSES",
  releaseStatuses: "RELEASE_STATUSES",
  releaseTypes: "RELEASE_TYPES",
  releaseApprovalDecisions: "RELEASE_APPROVAL_DECISIONS",
  documentCategories: "DOCUMENT_CATEGORIES",
  documentTypes: "DOCUMENT_TYPES",
  userRoles: "USER_ROLES",
  userStatuses: "USER_STATUSES",
  workItemRoles: "WORK_ITEM_ROLES",
  aiJobStatuses: "AI_JOB_STATUSES",
};

function renderArray(values) {
  return `[\n${values.map((value) => `  ${JSON.stringify(value)},`).join("\n")}\n] as const`;
}

function renderServerEnums(enums = publicEnums()) {
  const lines = [
    "// Generated by `npm run generate:enums -w web`.",
    "// Source of truth: api/src/domain/enums.js",
    "// Do not edit manually; edit the backend enum source and regenerate.",
    "",
  ];

  for (const [key, exportName] of Object.entries(EXPORT_NAMES)) {
    const values = enums[key];
    if (!Array.isArray(values)) {
      throw new Error(`Missing enum array: ${key}`);
    }
    lines.push(`export const ${exportName} = ${renderArray(values)};`);
    lines.push("");
  }

  lines.push("export const SERVER_ENUMS = {");
  for (const [key, exportName] of Object.entries(EXPORT_NAMES)) {
    lines.push(`  ${key}: ${exportName},`);
  }
  lines.push("} as const;");
  lines.push("");
  lines.push("export type ServerEnumName = keyof typeof SERVER_ENUMS;");
  lines.push("export type ServerEnumValue<T extends ServerEnumName> = (typeof SERVER_ENUMS)[T][number];");
  lines.push("");

  return lines.join("\n");
}

function writeServerEnums() {
  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, renderServerEnums(), "utf8");
}

if (require.main === module) {
  writeServerEnums();
  console.log(`Generated ${path.relative(process.cwd(), OUTPUT_FILE)}`);
}

module.exports = {
  EXPORT_NAMES,
  OUTPUT_FILE,
  renderServerEnums,
  writeServerEnums,
};
