import React from 'react';
import { Bot, X } from 'lucide-react';

// ---------------------------------------------------------------------------
// AiSidebar: context-aware AI analysis panel
// ---------------------------------------------------------------------------

export interface AiSidebarRisk {
  text: string;
  level: 'risk' | 'warning' | 'info';
}

export interface AiSidebarEvidence {
  source: string;
  quote: string;
}

interface AiSidebarProps {
  /** Context subtitle, e.g. "Dashboard overview" */
  contextSubtitle?: string;
  /** Summary text generated by AI */
  summary?: string;
  /** List of identified risks */
  risks?: AiSidebarRisk[];
  /** List of recommendations */
  recommendations?: string[];
  /** Evidence references */
  evidence?: AiSidebarEvidence[];
  /** Called when user confirms AI suggestions */
  onConfirm?: () => void;
  /** Called when user wants to edit AI output */
  onEdit?: () => void;
  /** Called when user dismisses AI suggestions */
  onIgnore?: () => void;
  /** Called when user closes the sidebar */
  onClose?: () => void;
  /** Additional CSS class */
  className?: string;
}

const AiSidebar: React.FC<AiSidebarProps> = ({
  contextSubtitle,
  summary,
  risks = [],
  recommendations = [],
  evidence = [],
  onConfirm,
  onEdit,
  onIgnore,
  onClose,
  className = '',
}) => {
  return (
    <aside className={`ai-sidebar ${className}`}>
      {/* Header */}
      <div className="ai-sidebar-header">
        <div className="ai-sidebar-title">
          <Bot size={18} />
          <span>AI Context</span>
        </div>
        {onClose && (
          <button
            className="topbar-icon-button"
            onClick={onClose}
            aria-label="Close AI sidebar"
          >
            <X size={16} />
          </button>
        )}
      </div>

      {/* Body */}
      <div className="ai-sidebar-body">
        {/* Context subtitle */}
        {contextSubtitle && (
          <div className="ai-sidebar-section">
            <div className="ai-sidebar-section-label">Context</div>
            <div className="ai-sidebar-summary">{contextSubtitle}</div>
          </div>
        )}

        {/* Summary */}
        {summary && (
          <div className="ai-sidebar-section">
            <div className="ai-sidebar-section-label">Summary</div>
            <div className="ai-sidebar-summary">{summary}</div>
          </div>
        )}

        {/* Risks */}
        {risks.length > 0 && (
          <div className="ai-sidebar-section">
            <div className="ai-sidebar-section-label">
              Risks ({risks.length})
            </div>
            {risks.map((risk, index) => (
              <div className="ai-sidebar-risk-item" key={index}>
                <span className={`ai-sidebar-risk-dot ${risk.level}`} />
                <span>{risk.text}</span>
              </div>
            ))}
          </div>
        )}

        {/* Recommendations */}
        {recommendations.length > 0 && (
          <div className="ai-sidebar-section">
            <div className="ai-sidebar-section-label">Recommendations</div>
            {recommendations.map((rec, index) => (
              <div className="ai-sidebar-recommendation" key={index}>
                {rec}
              </div>
            ))}
          </div>
        )}

        {/* Evidence */}
        {evidence.length > 0 && (
          <div className="ai-sidebar-section">
            <div className="ai-sidebar-section-label">Evidence</div>
            {evidence.map((ev, index) => (
              <div className="ai-sidebar-evidence" key={index}>
                <strong>{ev.source}</strong>
                <div style={{ marginTop: 4 }}>{ev.quote}</div>
              </div>
            ))}
          </div>
        )}

        {/* Action buttons */}
        {(onConfirm || onEdit || onIgnore) && (
          <div className="ai-sidebar-actions">
            {onConfirm && (
              <button className="btn btn-primary btn-sm" onClick={onConfirm}>
                Confirm
              </button>
            )}
            {onEdit && (
              <button className="btn btn-secondary btn-sm" onClick={onEdit}>
                Edit
              </button>
            )}
            {onIgnore && (
              <button className="btn btn-text btn-sm" onClick={onIgnore}>
                Ignore
              </button>
            )}
          </div>
        )}
      </div>
    </aside>
  );
};

export default AiSidebar;
