// ---------------------------------------------------------------------------
// Stable async-query namespaces and mutation invalidation groups.
//
// useAsync entries are keyed by these namespaces. Mutations opt into one of
// the named groups below instead of inferring affected data from URL text.
// ---------------------------------------------------------------------------

export const queryKeys = {
  aiCapabilities: 'ai:capabilities',
  aiSummary: 'ai:summary',
  auditLogs: 'audit:logs',
  capacityCalendar: 'capacity:calendar',
  capacityOverview: 'capacity:overview',
  dashboardOverview: 'dashboard:overview',
  defectsList: 'defects:list',
  deliveryBuilds: 'delivery:builds',
  deliveryGates: 'delivery:gates',
  deliveryReleaseApprovals: 'delivery:release-approvals',
  deliveryReleaseReport: 'delivery:release-report',
  deliveryReleases: 'delivery:releases',
  deliveryRollbackRecords: 'delivery:rollback-records',
  documentsList: 'documents:list',
  flowOverview: 'flow:overview',
  myWorkCapacity: 'mywork:capacity',
  myWorkDashboard: 'mywork:dashboard',
  myWorkWeeklySummary: 'mywork:weekly-summary',
  organizationDepartments: 'organization:departments',
  portfoliosList: 'portfolios:list',
  productPrograms: 'programs:list',
  productsList: 'products:list',
  projectFlow: 'project:flow',
  projectWorkflowBinding: 'project:workflow-binding',
  projectsDecisions: 'projects:decisions',
  projectsDelivery: 'projects:delivery',
  projectsDetail: 'projects:detail',
  projectsKanban: 'projects:kanban',
  projectsList: 'projects:list',
  projectsMembers: 'projects:members',
  projectsRisks: 'projects:risks',
  requirementsDetail: 'requirements:detail',
  requirementsList: 'requirements:list',
  settingsAiAssistant: 'settings:ai-assistant',
  settingsAiProvider: 'settings:ai-provider',
  sprintsBurndown: 'sprints:burndown',
  sprintsCommitment: 'sprints:commitment',
  sprintsScopeChanges: 'sprints:scope-changes',
  strategicGoalsList: 'strategic-goals:list',
  tasksStatusHistory: 'tasks:status-history',
  teamMembers: 'team:members',
  testCasesList: 'test-cases:list',
  testingQualitySnapshot: 'testing-quality:snapshot',
  timeEntriesList: 'time-entries:list',
  workLogsTeam: 'work-logs:team',
  workLogsWeeklySummary: 'work-logs:weekly-summary',
  workflowTemplates: 'workflow:templates',
} as const;

export type AsyncQueryKey = (typeof queryKeys)[keyof typeof queryKeys];

function keys<const T extends readonly AsyncQueryKey[]>(...values: T): T {
  return values;
}

export const mutationInvalidationKeys = {
  aiAssistant: keys(
    queryKeys.aiSummary,
    queryKeys.settingsAiAssistant,
    queryKeys.auditLogs,
  ),
  aiCapabilityInvocation: keys(
    queryKeys.aiCapabilities,
    queryKeys.aiSummary,
    queryKeys.auditLogs,
  ),
  aiJobs: keys(
    queryKeys.aiSummary,
    queryKeys.dashboardOverview,
    queryKeys.documentsList,
    queryKeys.auditLogs,
  ),
  aiProvider: keys(
    queryKeys.aiSummary,
    queryKeys.settingsAiAssistant,
    queryKeys.settingsAiProvider,
    queryKeys.auditLogs,
  ),
  capacity: keys(
    queryKeys.capacityCalendar,
    queryKeys.capacityOverview,
    queryKeys.dashboardOverview,
    queryKeys.myWorkCapacity,
    queryKeys.projectsList,
    queryKeys.auditLogs,
  ),
  delivery: keys(
    queryKeys.dashboardOverview,
    queryKeys.deliveryBuilds,
    queryKeys.deliveryGates,
    queryKeys.deliveryReleaseApprovals,
    queryKeys.deliveryReleaseReport,
    queryKeys.deliveryReleases,
    queryKeys.deliveryRollbackRecords,
    queryKeys.projectsDelivery,
    queryKeys.projectsDetail,
    queryKeys.projectsList,
    queryKeys.auditLogs,
  ),
  documents: keys(
    queryKeys.aiSummary,
    queryKeys.documentsList,
    queryKeys.projectsList,
    queryKeys.auditLogs,
  ),
  products: keys(
    queryKeys.dashboardOverview,
    queryKeys.productPrograms,
    queryKeys.portfoliosList,
    queryKeys.productsList,
    queryKeys.projectsDelivery,
    queryKeys.projectsDetail,
    queryKeys.projectsList,
    queryKeys.strategicGoalsList,
    queryKeys.auditLogs,
  ),
  projects: keys(
    queryKeys.capacityOverview,
    queryKeys.dashboardOverview,
    queryKeys.flowOverview,
    queryKeys.myWorkDashboard,
    queryKeys.projectFlow,
    queryKeys.projectWorkflowBinding,
    queryKeys.projectsDecisions,
    queryKeys.projectsDelivery,
    queryKeys.projectsDetail,
    queryKeys.projectsKanban,
    queryKeys.projectsList,
    queryKeys.projectsMembers,
    queryKeys.projectsRisks,
    queryKeys.testingQualitySnapshot,
    queryKeys.auditLogs,
  ),
  projectTasks: keys(
    queryKeys.capacityOverview,
    queryKeys.dashboardOverview,
    queryKeys.flowOverview,
    queryKeys.myWorkDashboard,
    queryKeys.projectFlow,
    queryKeys.projectWorkflowBinding,
    queryKeys.projectsDecisions,
    queryKeys.projectsDelivery,
    queryKeys.projectsDetail,
    queryKeys.projectsKanban,
    queryKeys.projectsList,
    queryKeys.projectsMembers,
    queryKeys.projectsRisks,
    queryKeys.sprintsBurndown,
    queryKeys.sprintsCommitment,
    queryKeys.sprintsScopeChanges,
    queryKeys.tasksStatusHistory,
    queryKeys.testingQualitySnapshot,
    queryKeys.auditLogs,
  ),
  requirements: keys(
    queryKeys.dashboardOverview,
    queryKeys.deliveryGates,
    queryKeys.myWorkDashboard,
    queryKeys.projectsDelivery,
    queryKeys.projectsDetail,
    queryKeys.projectsList,
    queryKeys.requirementsDetail,
    queryKeys.requirementsList,
    queryKeys.auditLogs,
  ),
  tasks: keys(
    queryKeys.dashboardOverview,
    queryKeys.flowOverview,
    queryKeys.myWorkDashboard,
    queryKeys.projectFlow,
    queryKeys.projectsDelivery,
    queryKeys.projectsDetail,
    queryKeys.projectsKanban,
    queryKeys.sprintsBurndown,
    queryKeys.sprintsCommitment,
    queryKeys.sprintsScopeChanges,
    queryKeys.tasksStatusHistory,
    queryKeys.auditLogs,
  ),
  team: keys(
    queryKeys.capacityOverview,
    queryKeys.dashboardOverview,
    queryKeys.organizationDepartments,
    queryKeys.teamMembers,
    queryKeys.auditLogs,
  ),
  testing: keys(
    queryKeys.dashboardOverview,
    queryKeys.defectsList,
    queryKeys.deliveryGates,
    queryKeys.myWorkDashboard,
    queryKeys.projectsDelivery,
    queryKeys.projectsDetail,
    queryKeys.projectsList,
    queryKeys.testCasesList,
    queryKeys.testingQualitySnapshot,
    queryKeys.auditLogs,
  ),
  timeEntries: keys(
    queryKeys.capacityOverview,
    queryKeys.dashboardOverview,
    queryKeys.myWorkCapacity,
    queryKeys.myWorkDashboard,
    queryKeys.timeEntriesList,
    queryKeys.auditLogs,
  ),
  workLogs: keys(
    queryKeys.capacityOverview,
    queryKeys.dashboardOverview,
    queryKeys.myWorkCapacity,
    queryKeys.myWorkDashboard,
    queryKeys.myWorkWeeklySummary,
    queryKeys.workLogsTeam,
    queryKeys.workLogsWeeklySummary,
    queryKeys.auditLogs,
  ),
  workflow: keys(
    queryKeys.flowOverview,
    queryKeys.projectFlow,
    queryKeys.projectWorkflowBinding,
    queryKeys.workflowTemplates,
  ),
} as const;

export type MutationInvalidation = keyof typeof mutationInvalidationKeys;
