const tasks = [
  {
    id: "TASK-118",
    title: "Payment callback integration",
    status: "blocked",
    statusText: "Blocked",
    projectId: "PRJ-001",
    owner: "Wang Jing",
    dueDate: "2026-06-23",
    requirementId: "REQ-204",
    progress: 62,
    blocker: "Signature fields differ from the latest design draft.",
    type: "task",
    parentId: null,
    wbsCode: "1.1",
    kanbanColumn: "blocked",
    sortOrder: 10,
    estimatedHours: 16,
    actualHours: 10,
  },
  {
    id: "TASK-121",
    title: "Daily work-log analysis validation",
    status: "running",
    statusText: "In progress",
    projectId: "PRJ-003",
    owner: "Li Chen",
    dueDate: "2026-06-23",
    requirementId: "REQ-231",
    progress: 48,
    blocker: null,
    type: "task",
    parentId: null,
    wbsCode: "1.2",
    kanbanColumn: "in_progress",
    sortOrder: 20,
    estimatedHours: 24,
    actualHours: 8,
  },
  {
    id: "TASK-132",
    title: "Project status field verification",
    status: "waiting",
    statusText: "Waiting for acceptance",
    projectId: "PRJ-005",
    owner: "Chen Xu",
    dueDate: "2026-06-24",
    requirementId: "REQ-196",
    progress: 88,
    blocker: null,
    type: "task",
    parentId: null,
    wbsCode: "2.1",
    kanbanColumn: "acceptance",
    sortOrder: 30,
    estimatedHours: 8,
    actualHours: 7,
  },
  {
    id: "TASK-136",
    title: "Bid response matrix template",
    status: "done",
    statusText: "Done",
    projectId: "PRJ-004",
    owner: "Zhao Qing",
    dueDate: "2026-06-22",
    requirementId: "REQ-220",
    progress: 100,
    blocker: null,
    type: "work_package",
    parentId: null,
    wbsCode: "3.1",
    kanbanColumn: "done",
    sortOrder: 40,
    estimatedHours: 12,
    actualHours: 12,
  },
];

const programs = [
  {
    id: "PGM-001",
    name: "AI Project Management Program",
    owner: "PMO",
    status: "active",
    healthScore: 82,
    progress: 64,
    projectIds: ["PRJ-001", "PRJ-003", "PRJ-005"],
    risks: ["Integration blocker in PRJ-001", "AI analysis workflow still in design"],
    updatedAt: "2026-06-23T09:30:00.000Z",
  },
];

const portfolios = [
  {
    id: "PFO-001",
    name: "Enterprise Collaboration Portfolio",
    owner: "Product Office",
    status: "active",
    productIds: ["PROD-001", "PROD-002"],
    roadmap: [
      { quarter: "Q3", focus: "MVP delivery and AI log analysis" },
      { quarter: "Q4", focus: "Document intelligence and resource scheduling" },
    ],
  },
];

const projects = [
  {
    id: "PRJ-001",
    name: "R&D Platform Phase 1",
    status: "development",
    healthScore: 82,
    owner: "Zhang San",
    progress: 64,
    riskCount: 3,
    updatedAt: "2026-06-23T09:30:00.000Z",
    milestones: [
      { name: "Requirement baseline", status: "done", date: "2026-06-10" },
      { name: "Integration test", status: "running", date: "2026-06-25" },
      { name: "Acceptance review", status: "planned", date: "2026-07-02" },
    ],
  },
  {
    id: "PRJ-002",
    name: "Customer Delivery Project A",
    status: "testing",
    healthScore: 76,
    owner: "Li Si",
    progress: 81,
    riskCount: 5,
    updatedAt: "2026-06-22T15:10:00.000Z",
    milestones: [
      { name: "Feature complete", status: "done", date: "2026-06-18" },
      { name: "Regression test", status: "running", date: "2026-06-26" },
      { name: "Customer signoff", status: "planned", date: "2026-07-05" },
    ],
  },
  {
    id: "PRJ-003",
    name: "Document AI Analysis Center",
    status: "design",
    healthScore: 88,
    owner: "Wang Wu",
    progress: 42,
    riskCount: 1,
    updatedAt: "2026-06-23T10:20:00.000Z",
    milestones: [
      { name: "Model workflow design", status: "running", date: "2026-06-28" },
      { name: "Private model routing", status: "planned", date: "2026-07-09" },
    ],
  },
  {
    id: "PRJ-004",
    name: "Organization Permission Upgrade",
    status: "acceptance",
    healthScore: 91,
    owner: "Zhou Ning",
    progress: 93,
    riskCount: 0,
    updatedAt: "2026-06-23T08:05:00.000Z",
    milestones: [
      { name: "Permission model", status: "done", date: "2026-06-12" },
      { name: "Acceptance closeout", status: "running", date: "2026-06-24" },
    ],
  },
  {
    id: "PRJ-005",
    name: "Product Roadmap Upgrade",
    status: "planning",
    healthScore: 79,
    owner: "Zhao Qing",
    progress: 28,
    riskCount: 2,
    updatedAt: "2026-06-21T12:00:00.000Z",
    milestones: [
      { name: "Version scope", status: "running", date: "2026-06-27" },
      { name: "Capacity review", status: "planned", date: "2026-07-04" },
    ],
  },
];

const products = [
  {
    id: "PROD-001",
    name: "Project Management Platform",
    owner: "Product Office",
    version: "1.0",
    stage: "MVP delivery",
    modules: ["Workspace", "Project portfolio", "Requirements", "Testing", "Documents", "Organization", "AI analysis"],
    roadmap: [
      { version: "1.0", target: "Task, project, requirement, document center", status: "development" },
      { version: "1.1", target: "Testing management and workflow gates", status: "planned" },
      { version: "1.2", target: "Document AI and work-log completion analysis", status: "design" },
      { version: "2.0", target: "Scheduling automation and knowledge-base assistant", status: "evaluating" },
    ],
  },
  {
    id: "PROD-002",
    name: "AI Analysis Center",
    owner: "AI Platform Team",
    version: "0.9",
    stage: "Design",
    modules: ["Document parsing", "Vector retrieval", "Model routing", "Evidence citation"],
    roadmap: [
      { version: "0.9", target: "Document summary and risk extraction", status: "design" },
      { version: "1.0", target: "Private model routing and audit log", status: "planned" },
    ],
  },
];

const requirements = [
  {
    id: "REQ-204",
    title: "Payment callback integration",
    status: "development",
    priority: "high",
    projectId: "PRJ-001",
    owner: "Wang Jing",
    completion: 73,
    linkedTasks: ["TASK-118"],
    acceptanceCriteria: ["Callback signature verified", "Failure callback cases covered", "Field compatibility confirmed"],
  },
  {
    id: "REQ-220",
    title: "Bid response matrix generation",
    status: "waiting_acceptance",
    priority: "medium",
    projectId: "PRJ-004",
    owner: "Zhao Qing",
    completion: 86,
    linkedTasks: ["TASK-136"],
    acceptanceCriteria: ["Upload bid document", "Extract clauses", "Generate response matrix"],
  },
  {
    id: "REQ-231",
    title: "Daily work-log requirement completion analysis",
    status: "testing",
    priority: "high",
    projectId: "PRJ-003",
    owner: "Li Chen",
    completion: 68,
    linkedTasks: ["TASK-121"],
    acceptanceCriteria: ["Extract completed items", "Identify blockers", "Update completion recommendation"],
  },
  {
    id: "REQ-242",
    title: "Project health scoring",
    status: "scheduled",
    priority: "medium",
    projectId: "PRJ-005",
    owner: "Chen Xu",
    completion: 31,
    linkedTasks: ["TASK-132"],
    acceptanceCriteria: ["Score projects by risk", "Expose portfolio summary", "Support drill-down"],
  },
];

const tests = [
  {
    id: "TEST-001",
    name: "Payment callback regression",
    requirementId: "REQ-204",
    projectId: "PRJ-001",
    status: "blocked",
    owner: "QA Team A",
    totalCases: 42,
    passedCases: 27,
    failedCases: 4,
    blockedCases: 11,
  },
  {
    id: "TEST-002",
    name: "Work-log analyzer API",
    requirementId: "REQ-231",
    projectId: "PRJ-003",
    status: "running",
    owner: "QA Team B",
    totalCases: 26,
    passedCases: 19,
    failedCases: 2,
    blockedCases: 5,
  },
  {
    id: "TEST-003",
    name: "Organization permission acceptance",
    requirementId: "REQ-220",
    projectId: "PRJ-004",
    status: "passed",
    owner: "QA Team C",
    totalCases: 33,
    passedCases: 33,
    failedCases: 0,
    blockedCases: 0,
  },
];

const sprints = [
  {
    id: "SPR-001",
    projectId: "PRJ-001",
    name: "Sprint 1",
    goal: "Deliver workspace and project execution loop",
    status: "active",
    startDate: "2026-06-17",
    endDate: "2026-06-30",
  },
];

const defects = [
  {
    id: "BUG-001",
    title: "Payment callback signature mismatch",
    status: "confirmed",
    severity: "high",
    projectId: "PRJ-001",
    requirementId: "REQ-204",
    assignee: "Wang Jing",
  },
];

const documents = [
  {
    id: "DOC-001",
    title: "Requirement Specification",
    type: "requirement",
    version: "v1.8",
    aiStatus: "analyzed",
    owner: "Product Office",
    updatedAt: "2026-06-23T07:40:00.000Z",
    linkedRequirements: ["REQ-204", "REQ-231"],
    risks: ["Payment callback field compatibility still requires owner confirmation."],
  },
  {
    id: "DOC-002",
    title: "Platform High-Level Design",
    type: "design",
    version: "v0.9",
    aiStatus: "needs_review",
    owner: "Architecture Team",
    updatedAt: "2026-06-22T16:00:00.000Z",
    linkedRequirements: ["REQ-242"],
    risks: ["Exception handling section is incomplete."],
  },
  {
    id: "DOC-003",
    title: "Customer Bid File",
    type: "bid",
    version: "v1.0",
    aiStatus: "parsing",
    owner: "Solution Team",
    updatedAt: "2026-06-21T11:30:00.000Z",
    linkedRequirements: ["REQ-220"],
    risks: ["Response matrix has not been generated."],
  },
  {
    id: "DOC-004",
    title: "Test Acceptance Report",
    type: "test",
    version: "v1.2",
    aiStatus: "analyzed",
    owner: "QA Team",
    updatedAt: "2026-06-21T17:20:00.000Z",
    linkedRequirements: ["REQ-204", "REQ-231"],
    risks: ["Two requirements are missing regression evidence."],
  },
];

const organization = {
  departments: [
    {
      id: "ORG-001",
      name: "Product Office",
      lead: "Zhang San",
      members: 9,
      load: 76,
      responsibilities: ["Requirement planning", "Roadmap", "Acceptance"],
    },
    {
      id: "ORG-002",
      name: "R&D Team 2",
      lead: "Wang Jing",
      members: 18,
      load: 91,
      responsibilities: ["Core platform", "Integration", "API services"],
    },
    {
      id: "ORG-003",
      name: "QA Center",
      lead: "Li Chen",
      members: 12,
      load: 84,
      responsibilities: ["Test plans", "Regression", "Acceptance evidence"],
    },
  ],
  people: [
    { id: "USR-001", name: "Zhang San", role: "Product Lead", departmentId: "ORG-001", activeProjects: 2 },
    { id: "USR-002", name: "Wang Jing", role: "Backend Engineer", departmentId: "ORG-002", activeProjects: 3 },
    { id: "USR-003", name: "Li Chen", role: "QA Lead", departmentId: "ORG-003", activeProjects: 2 },
    { id: "USR-004", name: "Zhao Qing", role: "Solution Manager", departmentId: "ORG-001", activeProjects: 2 },
  ],
};

const workLogs = [];
const aiJobs = [];

const aiSummaries = {
  dashboard: {
    title: "Workspace summary",
    summary:
      "There are 12 active tasks today, with 5 completed, 2 overdue, and 1 blocked. Payment callback integration should be handled first.",
    risks: [
      "REQ-204 still has a compatibility decision pending.",
      "Testing evidence is missing for two requirements.",
      "One integration blocker has lasted more than one day.",
    ],
    recommendations: [
      "Confirm payment callback compatibility with the product owner.",
      "Add abnormal callback test cases before acceptance.",
      "Link work-log findings back to REQ-204 and REQ-231.",
    ],
  },
  projects: {
    title: "Project portfolio summary",
    summary:
      "The portfolio has one high-risk project and two medium-risk projects. Most risk comes from test blockers and requirement changes.",
    risks: ["Customer Delivery Project A has a low defect closure rate.", "Product Roadmap Upgrade lacks confirmed milestones."],
    recommendations: ["Review testing capacity this week.", "Freeze the next version scope before adding new requirements."],
  },
  requirements: {
    title: "Requirement completion summary",
    summary:
      "The four tracked requirements average 64.5% completion. REQ-231 needs stronger testing evidence before acceptance.",
    risks: ["REQ-204 has a blocker that caps completion.", "REQ-242 is not decomposed enough for reliable execution."],
    recommendations: ["Split REQ-242 into executable tasks.", "Require evidence links before moving requirements to acceptance."],
  },
};

module.exports = {
  programs,
  portfolios,
  tasks,
  projects,
  products,
  requirements,
  tests,
  sprints,
  defects,
  documents,
  workLogs,
  aiJobs,
  organization,
  aiSummaries,
};
